name: Price-Crawler

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 8 * * SUN"

jobs:
  crawl-justclimb:
    name: Crawl JustClimb Price
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Setup Python
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: Gr1N/setup-poetry@v4
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - run: poetry --version

      - name: Install dependencies
        run: poetry install

      - name: Run crawler
        run: ./crawl.sh justclimb

      - name: Commit and publish result
        uses: EndBug/add-and-commit@v5
        with:
          add: "docs/justclimb.json"
          author_name: GitHub Action
          author_email: elcchan99@gmail.com
          branch: gh-pages
          message: "Update justclimb crawl result"
          pull_strategy: "--rebase"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  crawl-vermcity:
    needs: crawl-justclimb
    name: Crawl Verm City Price
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Setup Python
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: Gr1N/setup-poetry@v4
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - run: poetry --version

      - name: Install dependencies
        run: poetry install

      - name: Run crawler
        run: ./crawl.sh vermcity

      - name: Commit and publish result
        uses: EndBug/add-and-commit@v5
        with:
          add: "docs/vermcity.json"
          author_name: GitHub Action
          author_email: elcchan99@gmail.com
          branch: gh-pages
          message: "Update vermcity crawl result"
          pull_strategy: "--rebase"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  crawl-atticv:
    needs: crawl-vermcity
    name: Crawl AtticV Price
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Setup Python
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: Gr1N/setup-poetry@v4
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - run: poetry --version

      - name: Install dependencies
        run: poetry install

      - name: Run crawler
        run: ./crawl.sh atticv

      - name: Commit and publish result
        uses: EndBug/add-and-commit@v5
        with:
          add: "docs/atticv.json"
          author_name: GitHub Action
          author_email: elcchan99@gmail.com
          branch: gh-pages
          message: "Update atticv crawl result"
          pull_strategy: "--rebase"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
