name: Price-Crawler

on:
  push:
    branches:
      - master

jobs:
    crawl-price:
      name: Crawl Price
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: action/checkout@v2

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python install poetry
            poetry install

        - name: Run JustClimb crawler
          run: ./crawl.sh justclimb

        - name: Commit and publish result
          uses: EndBug/add-and-commit@v5
          with:
            add: 'docs/justclimb.json'
            author_name: GitHub Action
            author_email: elcchan99@gmail.com
            message: 'Update crawl result'
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}





